#!/usr/bin/env bash

echo "Installing tools"

# nice cli stuff
sudo pacman -S --noconfirm --needed xz ripgrep fzf eza man jq yq less

# Git stuff
sudo pacman -S --noconfirm --needed git github-cli lazygit
git config --global user.email "24865872+octothorped@users.noreply.github.com"
git config --global user.name "octothorped"

# Docker
sudo pacman -S --noconfirm --needed docker lazydocker
sudo systemctl enable docker.service
sudo systemctl start docker.service
sudo usermod -aG docker $USER
sudo pacman -S --noconfirm --needed docker-compose

echo "Completed installing tools"

echo "Installing languages"

sudo pacman -S --noconfirm --needed mise
mise use -g node@20 go

echo "Completed installing languages"
